// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzpnxibfecsqpombmwha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cG54aWJmZWNzcXBvbWJtd2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzA5ODcsImV4cCI6MjA2MzkwNjk4N30.Ah-dBJ_ru54LP4Haoe1b5ZoU7TyP9Qly4Cd0dysjUOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);